schema_version = 0

[pkg]
name = "bash"
supported_platforms = ["windows-x86_64"]
version = "5.2.37-0"
build_depends = []
depends = ["msys2-runtime"]

[input]
source_version = "5.2.37"
sha256 = "9599b22ecd1d5787ad7d3b7bf0c59f312b3396d1e281175dd1f8a4014da621ff"
tarball_root_dir = "bash-5.2.37"
tarball_compression = "gz"
image_type = "bootstrap_msys"
patches = [
    "sv_home_return_type.patch",
    "sh-setlinebuf-decl.patch"
]

[rules]
default = [
    { env = { "CFLAGS" = "-std=gnu17" }, rule = "bash ./configure --prefix ${cimple_output_dir}/usr"},
    "make -j${cimple_parallelism}",
    "make install",
    "ln -s ${cimple_image_dir}/usr/bin/bash.exe ${cimple_output_dir}/usr/bin/sh.exe",
]
