schema_version = 0

[pkg]
name = "make"
supported_platforms = ["windows-x86_64"]
version = "4.4-0"
build_depends = []
depends = ["msys2-runtime"]

[input]
source_version = "4.4"
sha256 = "581f4d4e872da74b3941c874215898a7d35802f03732bdccee1d4a7979105d18"
tarball_root_dir = "make-4.4"
tarball_compression = "gz"
image_type = "bootstrap_msys"
patches = [
    "getenv-getopt-signature.patch"
]

[rules]
default = [
    "bash ./configure --prefix ${cimple_output_dir}",
    "make -j${cimple_parallelism}",
    "make install-exec"
]
